### ISSUE TITLE
播放4k时断流，非4k没有问题

### ISSUE THREAD

**Issue by santaclausbaby** [0oVicero0/serverSpeeder_Install#12]
非常奇怪。其实1440p时带宽和4k差不多的，但4k就断流

**Comment by 0oVicero0** [comment]
是不是机子的吞吐问题？

**Comment by santaclausbaby** [comment]
我是独服，开的1g口，下载什么的全速没有问题。那您看看有什么方法能测试吞吐问题？

**Comment by 0oVicero0** [comment]
尝试优化下sysctl.conf中的参数
优化一下锐速的配置文件:
尝试调整l2wQLimit，w2lQLimit，initialCwndWan
的参数.

**Comment by santaclausbaby** [comment]
两个limit我一直是512 4096，CWND我是默认的22。sysctl里没有内容…

**Comment by 0oVicero0** [comment]
cwnd调大一点试试

获取 Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by santaclausbaby** [comment]
好的，我晚上回去测试一下。一般调大到多少？有没有算法能确定这个数值？
