### ISSUE TITLE
2.6.32-504.3.3.el6.x86_64的问题

### ISSUE THREAD

**Issue by z991238** [0oVicero0/serverSpeeder_Install#14]
2.6.32-504.3.3.el6.x86_64。二进制如何更新到3.11.20.10呢，用二进制命令更新最高提示只到3.11.20.4，我看内核安装列表里面有3.11.20.10的支持

**Comment by 0oVicero0** [comment]
下载对应的二进制文件，按命名规则重命名，在配置文件里替换旧的二进制文件。重启

**Comment by z991238** [comment]
你好。想在咨询一下。就是哪里有这个二进制文件下载呢。我也找不到。而且我也不知道微软的机子如何操作更换内核
