### ISSUE TITLE
Request for binary update

### ISSUE THREAD

**Issue by legendtang** [0oVicero0/serverSpeeder_Install#7]
http://download.appexnetworks.com.cn/releaseNotes/

Current version on Ubuntu 16.04 are very likely to raise kernel panic. I've seen several machines occur the crashing. Please update to latest binary. Thank you!

**Comment by 0oVicero0** [comment]
The all of binary are collected in internet.
I can not found the latest binary.

**Comment by legendtang** [comment]
Since it cause kernel crashes, please just left this issue open before new binaries arrive.
